In [2]:
import requests

In [4]:
url="https://stephen-king-api.onrender.com/api/books"
response = requests.get(url)
if response.status_code == 200:
    print("Request was successful.")
print(response.status_code)

Request was successful.
200

In [15]:

data=response.json()

In [13]:
import pandas as pd
df=pd.json_normalize(data["data"])
df.head(10)
df.set_index("id", inplace=True)
df

,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
id,,,,,,,,,
1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...
60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [10]:
import requests

url = "https://meowfacts.herokuapp.com/"
response = requests.get(url)

if response.status_code == 200:
    print("Request was successful.")

data = response.json()
print(data["data"])

Request was successful.
['In ancient Egypt, when a family cat died, all family members would shave their eyebrows as a sign of mourning.']

In [28]:
import requests
import pandas as pd

url = "http://universities.hipolabs.com/search?country=Pakistan"
response = requests.get(url)
data = response.json()
df = pd.json_normalize(data)
df = df[["name", "country", "web_pages"]]
df.head(50)

,name,country,web_pages
0,"Information Technology University, Lahore",Pakistan,[https://itu.edu.pk/]
1,Abasyn University Peshawar,Pakistan,[http://www.abasyn.edu.pk/]
2,Allama Iqbal Open University,Pakistan,[http://www.aiou.edu.pk/]
3,Azad Jammu and Kashmir University,Pakistan,[http://www.ajku.edu.pk/]
4,Aga Khan University,Pakistan,[http://www.aku.edu/]
5,Jamia Al Dirasat Ul Islami Karachi,Pakistan,[http://www.aldirasat.edu.pk/]
6,Al-Khair University,Pakistan,[http://www.alkhair.edu.pk/]
7,Ahmed Medical Institute,Pakistan,[http://www.ami.edu.pk/]
8,Air University,Pakistan,[http://www.au.edu.pk/]
9,"The University of Agriculture, Peshawar",Pakistan,[http://www.aup.edu.pk/]
10,Bahria University,Pakistan,[http://www.bahria.edu.pk/]
11,Barani Institute of Information Technology,Pakistan,[http://www.biit.edu.pk/]
12,Barani Institute of Management Sciences,Pakistan,[http://www.bims.edu.pk/]
13,Baqai Medical University,Pakistan,[https://baqai.edu.pk/]
14,Balochistan University of Engineering and Tech...,Pakistan,[http://www.buetk.edu.pk/]
15,Balochistan University of Information Technolo...,Pakistan,[http://www.buitms.edu.pk/]
16,"Bahauddin Zakariya University, Multan",Pakistan,[http://www.bzu.edu.pk/]
17,Capital University of Science & Technology,Pakistan,[https://cust.edu.pk/]
18,College of Business Management (CBM),Pakistan,[https://cbm.iobm.edu.pk/]
19,Cecos Univeristy of Information Technology,Pakistan,[http://www.cecos.edu.pk/]
20,"COMSATS Institute of Information Technology, A...",Pakistan,[http://www.ciit-atd.edu.pk/]
21,"COMSATS Institute of Information Technology, A...",Pakistan,[http://www.ciit-attock.edu.pk/]
22,COMSATS Institute of Information Technology,Pakistan,[http://www.ciit.edu.pk/]
23,"COMSATS Institute of Information Technology, L...",Pakistan,[http://www.ciitlahore.edu.pk/]
24,"COMSATS Institute of Information Technology, Wah",Pakistan,[http://www.ciit-wah.edu.pk/]
25,COSMIQ Institute of Technology,Pakistan,[http://www.cosmiq.edu.pk/]
26,Dadabhoy Institute of Higher Education,Pakistan,[http://www.dadabhoy.edu.pk/]
27,Dawood College of Engineering and Technology,Pakistan,[http://www.dcet.edu.pk/]
28,Dow University of Health Sciences,Pakistan,[http://www.duhs.edu.pk/]
29,Faisalabad Institute of Textile and Fashion De...,Pakistan,[http://www.fitfd.edu.pk/]
30,"Federal Urdu University of Arts,Science and Te...",Pakistan,[http://www.fuuast.edu.pk/]
31,Shaheed Benazir Bhutto Women University,Pakistan,[http://www.fwu.edu.pk/]
32,Gandhara Institute of Medical Sciences,Pakistan,[http://www.gandhara.edu.pk/]
33,Government College University Lahore,Pakistan,[http://www.gcu.edu.pk/]
34,Government College University Faisalabad,Pakistan,[http://www.gcuf.edu.pk/]
35,University of Balochistan,Pakistan,[http://www.uob.edu.pk/]
36,Zia-ud-Din University,Pakistan,[https://zu.edu.pk/]
37,Gift University,Pakistan,[http://www.gift.edu.pk/]
38,Ghulam Ishaq Khan Institute of Science & Techn...,Pakistan,[http://www.giki.edu.pk/]
39,Gangdara Institute Of Science & Technology,Pakistan,[http://www.gist.edu.pk/]
40,The Global College Lahore,Pakistan,[http://www.global.edu.pk/]
41,Gomal University,Pakistan,[http://www.gu.edu.pk/]
42,Greenwich University,Pakistan,[http://www.guic.edu.pk/]
43,Hajvery University Lahore for Women,Pakistan,[http://www.hajvery.edu.pk/]
44,Hamdard University,Pakistan,[http://www.hamdard.edu.pk/]
45,Hitec University,Pakistan,[http://www.hitecuni.edu.pk/]
46,Hazara University,Pakistan,[http://www.hu.edu.pk/]
47,Institute of Business Administration (IBA),Pakistan,[http://www.iba.edu.pk/]
48,Institute of Business Administration Sukkur,Pakistan,[http://www.iba-suk.edu.pk/]
49,Institute of Industrial Electronics Engineering,Pakistan,[http://www.iiee.edu.pk/]

In [37]:
API_KEY = "YOUR_API_KEY_HERE"
url=f"https://generativelanguage.googleapis.com/v1beta/{{name=files/*}}?key={API_KEY}"
response = requests.get(url)
if response.status_code == 200:
    print("Request was successful.")
    data = response.json()

print(data)

{'agents': []}

In [ ]:

import requests
import json

API_KEY = "YOUR_NEW_API_KEY_HERE"

url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={API_KEY}"

payload = {
    "contents": [{
        "parts": [{"text": "Tell me 3 facts about Pakistan"}]
    }]
}

response = requests.post(url, json=payload)
data = response.json()
print(data["candidates"][0]["content"]["parts"][0]["text"])