In [1]:
print("hello")

hello

In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv('global_air_quality_data_10000.csv')
data.loc[3:10,["City","NO2"]]

              City    NO2
3           Mumbai  10.96
4            Paris  76.85
5      Los Angeles  86.17
6            Tokyo  12.99
7         New York  92.01
8            Tokyo  10.13
9           London  92.98
10  Rio de Janeiro  38.10

In [17]:
# data [data["O3"]>100[["city","O3"]]
data[data["O3"] > 100][["City", "O3"]]
data[data["Humidity"]>99][["City","Humidity"]]

                City  Humidity
3             Mumbai     99.97
80    Rio de Janeiro     99.66
96           Toronto     99.24
102           Sydney     99.58
152           Moscow     99.63
...              ...       ...
9398     Los Angeles     99.71
9444           Tokyo     99.15
9659     Los Angeles     99.56
9916    Johannesburg     99.70
9945     Los Angeles     99.23

[103 rows x 2 columns]

In [28]:
# data[(data["Temperature"]>31) & (data["PM10"]>31)]
# data[(data["Temperature"] > 31) & (data["NO2"] > 50)]
data[(data["Temperature"]>32) & (data["Humidity"]>37.2)]
pm10=data[data["PM10"]>80]
pm10.iloc[8]
pm10.loc[8]

City                Tokyo
Country             Japan
Date           2023-09-21
PM2.5              131.46
PM10               145.57
NO2                 10.13
SO2                  25.1
CO                   9.08
O3                 181.72
Temperature          -6.2
Humidity            71.42
Wind Speed          16.81
Name: 8, dtype: object

In [30]:
data.head(10)

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
5,Los Angeles,USA,2023-01-05,121.28,196.39,86.17,28.74,2.64,46.86,18.53,43.01,3.96
6,Tokyo,Japan,2023-09-17,118.76,15.69,12.99,39.05,3.04,15.75,-1.37,17.76,17.66
7,New York,USA,2023-11-23,72.52,23.43,92.01,15.26,4.57,106.50,32.14,76.57,9.42
8,Tokyo,Japan,2023-09-21,131.46,145.57,10.13,25.10,9.08,181.72,-6.20,71.42,16.81
9,London,UK,2023-09-13,64.71,92.84,92.98,36.40,3.68,88.44,19.80,45.92,2.56

In [ ]:
data.query("PM10>90 & Temperature>30")[["City","Country"]]

                City   Country
57    Rio de Janeiro    Brazil
63          New York       USA
66          Istanbul    Turkey
69          Istanbul    Turkey
78    Rio de Janeiro    Brazil
...              ...       ...
9962         Toronto    Canada
9969         Beijing     China
9981     Los Angeles       USA
9994         Bangkok  Thailand
9997          Moscow    Russia

[1130 rows x 2 columns]

In [35]:
data[(data["PM10"] > 90) & (data["Temperature"] > 30)][["City", "Country"]]

                City   Country
57    Rio de Janeiro    Brazil
63          New York       USA
66          Istanbul    Turkey
69          Istanbul    Turkey
78    Rio de Janeiro    Brazil
...              ...       ...
9962         Toronto    Canada
9969         Beijing     China
9981     Los Angeles       USA
9994         Bangkok  Thailand
9997          Moscow    Russia

[1130 rows x 2 columns]