In [47]:
import mysql.connector
import numpy as np
import pandas as pd

db=mysql.connector.connect(
    host="localhost",
        user="root",
        password="",
        database="school_db"
)
print("database cannected")

database cannected

In [48]:
query="SELECT * FROM students"
df=pd.read_sql(query,db)
df.head()
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        20 non-null     int64
 1   name      20 non-null     str
 2   roll_no   20 non-null     str
 3   subject1  20 non-null     int64
 4   subject2  20 non-null     int64
 5   subject3  20 non-null     int64
dtypes: int64(4), str(2)
memory usage: 1.1 KB

C:\Users\itxab\AppData\Local\Temp\ipykernel_15412\39414445.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query,db)

    id          name roll_no  subject1  subject2  subject3
0    1      Ali Khan    S001        85        78        92
1    2     Ahmed Ali    S002        72        81        76
2    3     Abid Khan    S003        91        88        95
3    4    Usman Shah    S004        67        74        70
4    5   Hamza Malik    S005        88        92        84
5    6   Bilal Ahmad    S006        76        69        81
6    7   Hassan Khan    S007        95        89        93
7    8    Saad Ullah    S008        64        72        68
8    9      Zain Ali    S009        82        86        79
9   10    Fahad Khan    S010        73        77        85
10  11    Ahsan Shah    S011        89        94        90
11  12   Waqas Ahmad    S012        58        65        61
12  13   Danish Khan    S013        80        75        83
13  14   Talha Malik    S014        92        87        96
14  15  Shahzaib Ali    S015        69        71        74
15  16  Ibrahim Khan    S016        86        90        88
16  17    Saif Ullah    S017        77        82        79
17  18  Junaid Ahmad    S018        63        68        72
18  19   Arslan Khan    S019        94        91        89
19  20     Noman Ali    S020        71        76        80

In [49]:
df["total"]=df['subject1']+df['subject2']+df['subject3']
max_marks=300
df['percentage']=(df['total']/max_marks)*100
df['percentage']=df['percentage'].round(2)

In [50]:

import numpy as np
def get_grade(percentage):
    if percentage >= 90:
        return 'A'
    elif percentage >= 80:
        return 'B'
    elif percentage >= 70:
        return 'C'
    elif percentage >= 60:
        return 'D'
    elif percentage >= 40:
        return 'E'
    else:
        return 'Fail'

In [62]:
df['grade']=df['percentage'].apply(get_grade)
percentages =df['percentage'].values
class_average = np.mean(percentages)
print("Class Average:", round(class_average, 2))
highest = np.max(percentages)
lowest = np.min(percentages)
print("Highest:", highest)
print("Lowest:", lowest)
std_dev = np.std(percentages)
print("Standard Deviation:", round(std_dev, 2))
topper_index = np.argmax(percentages)   # highest value ka index
topper = df.iloc[topper_index]
print("Topper:", topper['name'], "-", topper['percentage'])
df

Class Average: 80.2
Highest: 92.33
Lowest: 61.33
Standard Deviation: 9.2
Topper: Hassan Khan - 92.33

,id,name,roll_no,subject1,subject2,subject3,total,percentage,grade,class_Avrage
0,1,Ali Khan,S001,85,78,92,255,85.00,B,80.1985
1,2,Ahmed Ali,S002,72,81,76,229,76.33,C,80.1985
2,3,Abid Khan,S003,91,88,95,274,91.33,A,80.1985
3,4,Usman Shah,S004,67,74,70,211,70.33,C,80.1985
4,5,Hamza Malik,S005,88,92,84,264,88.00,B,80.1985
5,6,Bilal Ahmad,S006,76,69,81,226,75.33,C,80.1985
6,7,Hassan Khan,S007,95,89,93,277,92.33,A,80.1985
7,8,Saad Ullah,S008,64,72,68,204,68.00,D,80.1985
8,9,Zain Ali,S009,82,86,79,247,82.33,B,80.1985
9,10,Fahad Khan,S010,73,77,85,235,78.33,C,80.1985
10,11,Ahsan Shah,S011,89,94,90,273,91.00,A,80.1985
11,12,Waqas Ahmad,S012,58,65,61,184,61.33,D,80.1985
12,13,Danish Khan,S013,80,75,83,238,79.33,C,80.1985
13,14,Talha Malik,S014,92,87,96,275,91.67,A,80.1985
14,15,Shahzaib Ali,S015,69,71,74,214,71.33,C,80.1985
15,16,Ibrahim Khan,S016,86,90,88,264,88.00,B,80.1985
16,17,Saif Ullah,S017,77,82,79,238,79.33,C,80.1985
17,18,Junaid Ahmad,S018,63,68,72,203,67.67,D,80.1985
18,19,Arslan Khan,S019,94,91,89,274,91.33,A,80.1985
19,20,Noman Ali,S020,71,76,80,227,75.67,C,80.1985